Add OpenTelemetry support to Graphistry K8s
graphistry/graphistry-helm pull request #63
Opened 2024-10-17 18:22 UTC by aucahuasi

This PR will add support for OpenTelemetry.
For more information see:
https://github.com/graphistry/graphistry-cli/blob/master/docs/telemetry.md

2024-11-20 00:45 UTC, aucahuasi commented
This is the PR for the documentation:
https://github.com/graphistry/graphistry-cli/pull/51

2024-11-21 15:25 UTC, webcoderz commented on charts/graphistry-helm/templates/telemetry/otel-collector.yaml
> +          image: otel/opentelemetry-collector-contrib:0.87.0
add helm templating to image and tag and control in values.yanl? makes updates easier?

2024-11-21 15:25 UTC, webcoderz commented on charts/graphistry-helm/templates/telemetry/prometheus-configmap.yaml
move to fork?

2024-11-21 15:26 UTC, webcoderz commented on charts/graphistry-helm/templates/telemetry/prometheus-ingress.yaml
tls conditionals

2024-11-21 15:29 UTC, webcoderz commented on charts/graphistry-helm/templates/telemetry/prometheus.yaml
prometheus fork again.. maybe?

2024-11-21 15:37 UTC, webcoderz commented on charts/values-overrides/examples/k3s_example_values.yaml
> +      kubernetes.io/ingress.class: traefik
this makes sense to do it this way versus hardcoded in other ingresses https://github.com/graphistry/graphistry-helm/blob/c0d809250b556d6ec01cce588d3a6fe5f90e660d/charts/graphistry-helm/templates/ingress/caddy-ingress.yml#L9 so maybe change the other ingresses to reflect this change

2024-11-22 22:34 UTC, aucahuasi commented on charts/graphistry-helm/templates/telemetry/grafana-ingress.yaml
Thanks, done!

2024-11-22 22:35 UTC, aucahuasi commented on charts/graphistry-helm/templates/telemetry/grafana.yaml
> +      serviceAccountName: job-robot
Thanks, done! I've removed the svc account from all telemetry deployments except the `otel-collector` (because it's using the wait-for containers)

2024-11-22 22:35 UTC, aucahuasi commented on charts/graphistry-helm/templates/telemetry/jaeger-ingress.yaml
Thanks, done!

2024-11-22 22:36 UTC, aucahuasi commented on charts/graphistry-helm/templates/telemetry/jaeger.yaml
> +      serviceAccountName: job-robot
Thanks, good catch! Done! Removed.

2024-11-29 21:51 UTC, aucahuasi commented on charts/graphistry-helm/templates/telemetry/dcgm-exporter.yaml
All observability tools are being managed by argo now.

2024-12-02 18:26 UTC, webcoderz commented on cd/argo-apps/templates/argo-cd.yaml
the path shouldnt have changed as this is using a forked argo, plus the charts-aux-bundled is not in the graphistry-helm repo so it would error out becasue wouldnt be able to find the config

2024-12-02 18:28 UTC, webcoderz commented on charts/graphistry-helm/charts/telemetry/Chart.yaml
just to note we can use the chart.yaml to generate docs with the comments beside the values in the respecitve values.yamls

2024-12-02 18:31 UTC, webcoderz reviewed
lgtm see the small comments on the argo configs, once those are good, can merge

2024-12-05 20:38 UTC, aucahuasi commented on charts/graphistry-helm/charts/telemetry/Chart.yaml
Yes, I added some basic docs mostly pointing to the official doc page:
https://github.com/graphistry/graphistry-cli/blob/master/docs/tools/telemetry.md#kubernetes-deployment

2024-12-05 20:48 UTC, aucahuasi commented on cd/argo-apps/templates/argo-cd.yaml
Good catch, done!

2024-12-05 20:48 UTC, aucahuasi commented on cd/argo-apps/templates/operators-cd-templates/postgres-operator-cd.yaml
Done, thanks!

2024-12-10 16:41 UTC, webcoderz requested changes
lgtm see minor comments

2024-12-10 16:41 UTC, webcoderz commented on cd/argo-apps/templates/operators-cd-templates/postgres-operator-cd.yaml
not sure this is going to work, argo is looking at the main repo, we dont keep these charts in our repo

2024-12-10 16:41 UTC, webcoderz commented on charts/graphistry-helm/charts/telemetry/files/grafana-config-files/provisioning/dashboards/node-exporter-dashboard.json.zip
a zip file?

2024-12-10 16:59 UTC, aucahuasi commented on cd/argo-apps/templates/operators-cd-templates/postgres-operator-cd.yaml
Good catch, I can change those references to again
`targetRevision: HEAD`
I've used the branch only for testing Argo.

2024-12-10 17:07 UTC, aucahuasi commented on cd/argo-apps/templates/operators-cd-templates/postgres-operator-cd.yaml
Done, with this commit:
https://github.com/graphistry/graphistry-helm/pull/63/commits/dd26e0262cc6cb2efc55e8f99aed0ba8460e9f48

2024-12-13 00:40 UTC, merged